apt-get -y remove --purge exim4*;
sed -i 's/#Port 22/Port 22222/g' /etc/ssh/sshd_config;
fallocate -l  2G /swapfile;
chmod 600 /swapfile;
mkswap /swapfile;
swapon /swapfile;
echo /swapfile none swap sw 0 0 >> /etc/fstab;
sysctl vm.swappiness=10;
sysctl vm.vfs_cache_pressure=50;
echo vm.swappiness = 10 >>/etc/sysctl.conf;
echo vm.vfs_cache_pressure = 50 >>/etc/sysctl.conf;
cd /tmp;
wget https://www.dotdeb.org/dotdeb.gpg;
apt-key add dotdeb.gpg;
rm dotdeb.gpg;
echo deb http://packages.dotdeb.org stretch all >> /etc/apt/sources.list;
echo deb-src http://packages.dotdeb.org stretch all >> /etc/apt/sources.list;
wget https://nginx.org/keys/nginx_signing.key;
apt-key add nginx_signing.key;
echo deb http://nginx.org/packages/debian/ stretch nginx >> /etc/apt/sources.list;
echo deb-src http://nginx.org/packages/debian/ stretch nginx >> /etc/apt/sources.list;
wget https://dev.mysql.com/get/mysql-apt-config_0.8.8-1_all.deb;
dpkg -i mysql-apt-config_0.8.8-1_all.deb;
rm mysql-apt-config_0.8.8-1_all.deb;
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash
apt-get -y autoremove;
apt-get -y autoclean;
apt-get -y update;
apt-get -y upgrade;
apt-get -y install -y nodejs nginx zip unzip mysql-server
wget -O- https://raw.github.com/ajenti/ajenti/1.x/scripts/install-debian.sh | sh;
sed -i 's/("Access-Control-Max-Age", 3600)/("Access-Control-Max-Age", "3600")/g' /usr/share/pyshared/socketio/transports.py;
sed -i 's/("Access-Control-Max-Age", 3600)/("Access-Control-Max-Age", "3600")/g' /usr/share/pyshared/socketio/handler.py;
apt-get -y install ajenti-v ajenti-v-mysql ajenti-v-ftp-pureftpd ajenti-v-nginx ajenti-v-nodejs;
npm i -g ghost-cli;
